development:
      host: localhost
      adapter: mysql
      database: fedena
      username: root
      password: 123456

test: &TEST
      adapter: sqlite3
      database: ":memory:"

production:
      host: localhost
      adapter: mysql
      database: fedena
      port: 3306
      username: admin
      password: 

cucumber:
  <<: *test
